template: templates/loz-script-project.yaml
overrides:
  artifacts:
    - type: script
      build_script:
        gh_name: terraform
        repo_name: linux-on-ibm-z-scripts
        path: src/build.sh
        args: --version 1.12.2
        docker_image: ubuntu:22.04
